### ISSUE TITLE
syncing across platforms

### ISSUE THREAD

**Issue by stanaquil** [ChangSpivey/MorphMan#9]
Thanks so much for the update to this useful tool - I never knew about the old version.

Is it possible to synchronize settings across more than one computer? I have Mac and Windows laptops, and it would be nice not to have to constantly remember if I've made a tweak to the preferences on one system or the other. If I even knew where the preferences file to copy from one system to another lives, that would help. I don't see it in the addon folder, but maybe it is buried somewhere.

Regarding the question about running on a mac, I am having no issues so far getting it to work on my mac, apart from the sync issue (it happens that I set it up on Windows first, I actually use the mac more).

I assume that the function of the add-on doesn't carry over to mobile devices like ipad and iphone, except to the extent that any extra fields and tags would be synchronized as normal.

**Comment by ChangSpivey** [comment]
Yep, thanks to @runiq this feature is already available in the development version (see PR #6 for details). To download the development version, go to the main page and click on `Clone or download -> Download ZIP`.  The rest stays the same as in release versions. Because the config location moved, you will have to enter your settings again.

You are right to assume that there is no way to install that plugin on Android/iOS - but by setting `review cards before new cards` (Android version), you can still do your daily reviews with your smartphone and than get the new/ordered cards at home (that's the way I do it).

Because I only own a single computer, I can't really test this sync functionality. Feedback whether it works as expected is highly appreciated! You can use this issue if you like.

**Comment by stanaquil** [comment]
Great, thanks! I downloaded the dev version and will definitely report any bugs I find.

I have another question now, but I'll put it in a separate "issue" for neatness. I'm new at this github stuff, so let me know if there are questions that would be more appropriate to ask on the forum.

**Comment by stanaquil** [comment]
Not intending to reopen the thread (unless you want to), but for the purposes of feedback: I just tried installing Anki on my work Mac and adding the same dev version of MorphMan to it. It has all my preferences intact, so the sync across platforms seems to be working well, except that when I run command-M, the number of known words at the top of the anki deck page comes up a little smaller than what it should be. I suspect it's not counting cards I marked "already-known". Is there a way to address this for syncing purposes?

**Comment by ChangSpivey** [comment]
Well, this value comes directly from the number know morphemes in the database. So if you add cards by external means, or delete cards (morphemes will still be in the `known morphemes database`), the size of that database can be different [`already known vocab` cards should make no difference - try renaming the dbs and recalculate].

Anki advises not to save to much extra data in the internal/synchronized storage... So synchronizing the databases is out of the question and tricks like taking the maximum of all devices can produce faulty values.

**Comment by stanaquil** [comment]
OK, thanks! I can just use the value on my primary laptop as the "true" value. As long as using one platform to review doesn't mess the other up, it'll be fine.

I was bewildered by the K number at first, but now I really like it. It's very motivating for me.
